version: '3'
services:
  sgxwallet:
    image: skalenetwork/sgxwalletsim:latest
    ports:
      - "1026:1026"
      - "1027:1027"
      - "1028:1028"
    volumes:
      - ./sgx_data:/usr/src/sdk/sgx_data
    restart: unless-stopped
    command: -s

