version: '3'
services:
  sgxwallet:
    image: skalenetwork/sgxwallet:latest
    ports:
      - "1026:1026"
      - "1027:1027"
      - "1028:1028"
    devices:
      - "/dev/isgx"
      - "/dev/mei0"
    volumes:
      - ./sgx_data:/usr/src/sdk/sgx_data
    restart: unless-stopped
    command: -s


