name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install packages
      run: >
        sudo apt-get update && sudo apt-get install -yq --no-install-recommends python-yaml vim telnet git
        ca-certificates build-essential ocaml ocamlbuild automake autoconf libtool wget python
        libssl-dev libssl-dev libcurl4-openssl-dev protobuf-compiler git libprotobuf-dev alien 
        cmake debhelper uuid-dev libxml2-dev libprotobuf10 cmake flex bison  libprocps-dev ccache 
        autoconf texinfo libssl-dev libboost-all-dev libjsonrpccpp-dev libjsonrpccpp-tools
    - name: install sgx
      run: >
        git clone -b sgx_2.5 --depth 1 https://github.com/intel/linux-sgx &&
        cd linux-sgx &&
        patch -p1 -i ../docker/install-psw.patch && ./download_prebuilt.sh 2> /dev/null 
        && make -s -j$(nproc) sdk_install_pkg psw_install_pkg 
        && sudo ./linux/installer/bin/sgx_linux_x64_sdk_2.5.100.49891.bin --prefix=/opt/intel
        && sudo ./linux/installer/bin/sgx_linux_x64_psw_2.5.100.49891.bin && 
        cd .. && rm -rf linux-sgx/          
    - name: build deps
      run:  cd scripts; build.py
    - name: build sgx
      run:  autoreconf -vif && automake && ./configure && make
