name: Build and push simulation mode container

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to docker
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p $GITHUB_TOKEN
      shell: bash
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file DockerfileSimulation --tag sgxcontainer:$(date +%s)
    - name: Push docker image
    - run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}:${$GITHUB_SHA}

