name: Build and push sim container

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to docker
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_SECRET }}
      run: docker login -u skalelabs -p ${GITHUB_TOKEN}
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file DockerfileSimulation --tag  skalenetwork/sgxwalletsim:latest
    - name: push docker image
      run:  docker push skalenetwork/sgxwalletsim:latest
    - name: run docker image
      run: docker run -d --network=host skalenetwork/sgxwalletsim:latest
    - name: sleep and checl
      run: sleep 3; ls sgx_data;

