name: Build and push base container
on:
  push:
    tags:
      - build_base*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to docker
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_SECRET }}
      run: docker login -u skalelabs -p ${GITHUB_TOKEN}
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file DockerfileBase --tag  skalenetwork/sgxwallet_base:latest
    - name: push docker image
      run:  docker push skalenetwork/sgxwallet_base:latest

