name: Build and push sim container

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to docker
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_SECRET }}
      run: docker login docker.pkg.github.com -u kladkogex -p ${GITHUB_TOKEN}
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file DockerfileSimulation --tag  docker.pkg.github.com/skalenetwork/sgxwallet/sgxwalletsim:latest
    - name: push docker image
      run:  docker push docker.pkg.github.com/skalenetwork/sgxwallet/sgxwalletsim:latest

