name: Build, test and push sim mode container
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Fail, if older Github Actions machine. Click "Re-run jobs"
      run: cat /proc/cpuinfo | grep avx512
    - name: Check that /dev/urandom exists
      run: ls /dev/urandom
    - name: Login to docker
      run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: Build and publish container for testing
      run: python3 scripts/docker_build.py DockerfileSimulation sgxwallet_sim ${GITHUB_SHA}
    - name: test
      run: python3 scripts/docker_test.py DockerfileSimulation sgxwallet_sim ${GITHUB_SHA}
    - name: build and deploy docker image
      if: |
            contains(github.ref, 'develop') || contains(github.ref, 'beta') ||
            contains(github.ref, 'master') ||
            contains(github.ref, 'SECURE_ENCLAVE_CHANGES')
      run : |
            sudo rm -rf /home/runner/work/sgxwallet/sgxwallet/sgx_data
            export BRANCH=${GITHUB_REF##*/}
            echo "Branch $BRANCH"
            export VERSION=$(cat VERSION)
            echo "Version $VERSION"
            export VERSION=$(bash ./scripts/calculate_version.sh $BRANCH $VERSION)
            echo "::set-env name=VERSION::$VERSION"
            echo "Version $VERSION"
            export RELEASE=true
            echo "::set-env name=RELEASE::$RELEASE"
            bash ./scripts/build_image.sh DockerfileSimulation sgxwallet_sim
            bash ./scripts/publish_image.sh sgxwallet_sim
      env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true



