name: Build and push sim container

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo ${GITHUB_REF##*/}
    - name: test3
      run: echo ${TAG}
    - name: Login to docker
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_SECRET }}
      run: docker login -u skalelabs -p ${GITHUB_TOKEN}
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: build and push
      run: python3 scripts/build_push.py

