name: Build, test and push release SGX container
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Fail, if older Github Actions machine. Click "Re-run jobs"
        run: cat /proc/cpuinfo | grep avx512
      - name: Login to docker
        run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - uses: actions/checkout@v1
      - name: submodule update
        run: git submodule update --init --recursive
      - name: build
        run: python3 scripts/docker_build.py Dockerfile sgxwallet ${GITHUB_SHA}
      - name: deploy docker image
        if: contains(github.ref, 'develop') || contains(github.ref, 'beta') || contains(github.ref, 'master') || contains(github.ref, 'stable')
        run : |
          export BRANCH=${GITHUB_REF##*/}
          echo "Branch $BRANCH"
          export VERSION=$(cat VERSION)
          echo "Version $VERSION"
          export VERSION=$(bash ./scripts/calculate_version.sh $BRANCH $VERSION)
          echo "::set-env name=VERSION::$VERSION"
          echo "Version $VERSION"
          export RELEASE=true
          echo "::set-env name=RELEASE::$RELEASE"
          bash ./scripts/build_image.sh DockerfileRelease sgxwallet_release
          bash ./scripts/publish_image.sh sgxwallet_release