name: Build base container
on:
  push:
    tags:
      - build_base*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to docker
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_SECRET }}
      run: docker login -u skalelabs -p ${GITHUB_TOKEN}
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file DockerfileBase --tag skalenetwork/sgxwallet_base:latest
    - name: deploy docker image
      if: contains(github.ref, 'develop') || contains(github.ref, 'beta') || contains(github.ref, 'master') || contains(github.ref, 'stable')
      run : |
        export BRANCH=${GITHUB_REF##*/}
        echo "Branch $BRANCH"
        export VERSION=$(cat VERSION)
        export VERSION=$(bash ./scripts/calculate_version.sh $BRANCH $VERSION sgxwallet_base)
        echo "::set-env name=VERSION::$VERSION"
        echo "Version $VERSION"
        export RELEASE=true
        echo "::set-env name=RELEASE::$RELEASE"
        bash ./scripts/build_and_publish.sh sgxwallet_base DockerfileBase