name: Build base container
on:
  push:
    tags:
      - build_base*
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - name: Fail, if older Github Actions machine
      run: cat /proc/cpuinfo | grep avv
    - name: Login to docker
      run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - uses: actions/checkout@v1
    - name: submodule update
      run: git submodule update --init --recursive
    - name: Build the Docker image
      run: docker build . --file DockerfileBase --tag skalenetwork/sgxwallet_base:latest && docker push skalenetwork/sgxwallet_base:latest
    - name: deploy docker image
      if: contains(github.ref, 'develop') || contains(github.ref, 'beta') || contains(github.ref, 'master') || contains(github.ref, 'stable')
      run : |
        export BRANCH=${GITHUB_REF##*/}
        echo "Branch $BRANCH"
        export VERSION=$(cat VERSION)
        echo "Version $VERSION"
        export VERSION=$(bash ./scripts/calculate_version.sh $BRANCH $VERSION)
        echo "::set-env name=VERSION::$VERSION"
        echo "Version $VERSION"
        export RELEASE=true
        echo "::set-env name=RELEASE::$RELEASE"
        bash ./scripts/build_image.sh DockerfileBase sgxwallet_base
        bash ./scripts/publish_image.sh sgxwallet_base